learner_user: learning
learner_user_home: /home/{{learner_user}}
dial_service_path: "{{learner_user_home}}/platform/service"
dial_home: "{{learner_user_home}}/platform/dial/sunbird-dial-service"
dial_root: "{{learner_user_home}}/platform/dial"
platform_api_url: "http://{{learningservice_ip}}:8080/learning-service"
instance: "{{env}}"
instance_name: sunbird
service_path: /home/{{learner_user}}/platform/service
script_name: "sunbird-dial-service"
script_dir: "{{ service_path }}"
grep_key: play.core.server.ProdServerStart
process: "/usr/bin/java"
service_args: "-Dconfig.file={{ dial_root }}/dial-service.conf"
process_home: ""
app_home: "{{ dial_home }}"
process_args: -- -cp '{{ app_home }}/lib/*' {{ service_args }} play.core.server.ProdServerStart {{ app_home }}
redis_port: 6379
dial_es_index_host: "{{ groups['composite-search-cluster']|join(':9200,')}}:9200"